# Generated by Django 5.1.4 on 2025-01-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_student_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='file',
            new_name='image',
        ),
    ]
